import Image from "next/image";
import Logo from "/public/graphics/logo-mark.svg";
import AboutIntro from "../../src/components/about/introComponent";
import SplashScreen from "../../src/components/about/splashScreenComponent";

export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
  openGraph: {
    title: "Blog",
  },
};

export default function about() {
 

  return (
    <>
      <SplashScreen />

      <header id="mbMenu" className="animate-element">
        <div className="mbMenuInner">
          <button
            // onclick="goTo(0);"
            className="button mbMenuLogo"
          >
            <Image
              className="logoWmb mark"
              src={Logo}
              alt="We Met Before Logo"
            />
          </button>
          <nav className="mbNavMenu">
            <ul className="mbNavList">
              <li className="mbNavItem">
                <button
                  className="mbNavButton"
                  // onclick="goTo(1);"
                >
                  <span className="mbNavTxt mbNavTxt2">Home</span>
                  <div className="mbMenuBol mbMenuBolStory"></div>
                </button>
              </li>
              <li className="mbNavItem">
                <button
                  className="mbNavButton"
                  // onclick="goTo(2);"
                >
                  <span className="mbNavTxt mbNavTxt3">Work</span>
                  <div className="mbMenuBol mbMenuBolWork"></div>
                </button>
              </li>
              <li className="mbNavItem">
                <button
                  className="mbNavButton"
                  // onclick="goTo(3);"
                >
                  <span className="mbNavTxt mbNavTxt4">Services</span>
                  <div className="mbMenuBol mbMenuBolServices"></div>
                </button>
              </li>
              <li className="mbNavItem">
                <button
                  className="mbNavButton"
                  // onclick="goTo(4);"
                >
                  <span className="mbNavTxt mbNavTxt5">Contact</span>
                  <div className="mbMenuBol mbMenuBolContact"></div>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </header> 
      
      <main>
        <section className="upperCircleRotateContainer">
          <div className="mbRotateLogoCirlce">
            <Image
              className="mbLogo"
              src="graphics/logo_white.svg"
              width={500}
              height={500}
              alt="We Met Before Logo"
            />
            <div className="mbCircle sphereGradient"></div>
            <div className="circleBlackBlur"></div>
          </div>
          <div className="mbStorySetTop">
            <div className="mbStoryCirBor mbStoryCirBor1"></div>
            <div className="mbStoryCirBor mbStoryCirBor2"></div>
            <div className="mbStoryTextContainer">
              <span className="mbStoryItem mbStoryTextYou">You</span>
              <span className="mbStoryItem mbStoryTextWork">Work</span>
              <span className="mbStoryItem mbStoryTextUs">Us</span>
            </div>
          </div>
          <div className="mbWelcomeTheIntro mbWelcomeTheIntro1">
            <h2 className="introTitle" id="introTitle1">
              Who we are
            </h2>
            <div className="introQouteContainer">
              <h3 id="introQoute">
                We are a digital-focused Amsterdam-based studio. Our
                multidisciplinary team of freelancers and an A.I. multiplies
                creative results and helps brands flourish.
              </h3>
            </div>
          </div>
          <div className="mbWelcomeTheIntro mbWelcomeTheIntro2">
            <h2 className="introTitle">We believe in co-creating</h2>
            <div className="introQouteContainer">
              <h3 id="introQoute">
                The new game is co-creation, which - in our case - can be broken
                down into three phases: Branding, Design, and Development.
              </h3>
            </div>
          </div>
        </section>

        <div id="smooth-content">
          <AboutIntro />

          <div id="anchorStory" className="mbStory"></div>

          {/* <section id="anchorWork" className="mbPortfolio">
            <ul className="mbPortfolioList">
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.plantiblefoods.com/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/plantible.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Plantible Foods"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">Plantible Foods</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">Development</p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.deeeuwigejeugd.nl/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/de-eeuwige-jeugd.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x De Eeuwige Jeugd"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">De Eeuwige Jeugd</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.livingcreations.com/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/living-creations.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Living Creations"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">Living Creations</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Branding, Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.onchainsmokers.com/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/on-chain-smokers-new.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x On Chain Smokers"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">On Chain Smokers</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Branding, Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.sinkit.org/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/sinkit.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Sinkit"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">Sinkit</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Featured Collaboration with [Loink missing here!]Moxie
                    Creatives – Brands with Purpose. We Met Before worked on
                    design & development.
                  </p>
                </a>
              </li>

              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.orderchamp.com/nl"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/orderchamp.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Orderchamp"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">Orderchamp</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">Branding</p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.debestuurskamer.nl/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/de-bestuurskamer-new.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x De Bestuurskamer"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">De Bestuurskamer</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Branding, Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.weareheroes.one/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/heroes.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x HEROES"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">HEROES</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://i-cam.nl/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/i-cam.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x i-Cam"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">i-Cam</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Branding, Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://moni.nl/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/moni.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Moni"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">Moni</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Branding, Design &amp; Development
                  </p>
                </a>
              </li>
              <li className="mbPortfolioItem">
                <a
                  className="mbPortfolioItem_link"
                  href="https://www.huijskenssassen.nl/"
                  target="_blank"
                >
                  <div className="mbPortfolioItem_imageWrapper">
                    <Image
                      className="mbPortfolioItem_image"
                      src="images/02072023/huijskens-sassen.jpg"
                      width={500}
                      height={500}
                      alt="We Met Before x Huijskens Sassen Communications"
                    />
                  </div>
                  <div className="mbPortfolioItem_content">
                    <h4 className="mbPortfolioItem_title">HSC</h4>
                    <span className="mbPortfolioItem_arrow">↗</span>
                  </div>
                  <p className="mbPortfolioItem_excerpt">
                    Design &amp; Development
                  </p>
                </a>
              </li>
            </ul>
          </section> */}

          {/* <section id="anchorServices" className="mbServicesContainerWrapper">
            <div className="mbServicesContainerIntro">
              <Image
                src="images/mb_astroid1.png"
                width={500}
                height={500}
                className="mbServicesIntro_Asteroid mbServicesIntro_Asteroid1"
                alt=""
              />
              <Image
                src="images/mb_astroid2.png"
                width={500}
                height={500}
                className="mbServicesIntro_Asteroid mbServicesIntro_Asteroid2"
                alt=""
              />
              <Image
                src="images/mb_astroid3.png"
                width={500}
                height={500}
                className="mbServicesIntro_Asteroid mbServicesIntro_Asteroid3"
                alt=""
              />
            </div>

            <div className="mbServicesContainer">
              <div className="mbServicesTopRow">
                <Image
                  src="assets/icons/icon_ai.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconBranding"
                  id="mbServiceIconBranding1"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_figma.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconBranding"
                  id="mbServiceIconBranding2"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_figma.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDesign"
                  id="mbServiceIconDesign1"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_ae.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDesign"
                  id="mbServiceIconDesign2"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_webflow.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDevelopment"
                  id="mbServiceIconDevelopment1"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_react.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDevelopment"
                  id="mbServiceIconDevelopment2"
                  alt=""
                />
              </div>

              <div className="mbServicesIntro_h2Container">
                <h2 className="mbServicesIntro_h2 is-desktop">Services</h2>
                <h2 className="mbServicesIntro_h2 is-mobile">Our services</h2>
              </div>

              <div className="services-carousel">
                <div
                  id="thumbnail-carousel"
                  className="splide services-carousel_thumb-splide"
                  aria-label="The carousel with thumbnails. Selecting a thumbnail will change the Beautiful Gallery carousel."
                >
                  <div className="splide__track">
                    <ul className="splide__list">
                      <li className="splide__slide services-carousel_thumb-slide">
                        <p className="services-carousel_thumb-title">
                          Branding
                        </p>
                      </li>
                      <li className="splide__slide services-carousel_thumb-slide">
                        <p className="services-carousel_thumb-title">Design</p>
                      </li>
                      <li className="splide__slide services-carousel_thumb-slide">
                        <p className="services-carousel_thumb-title">
                          Development
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
                <div
                  id="main-carousel"
                  className="splide"
                  aria-label="The carousel with thumbnails. Selecting a thumbnail will change the Beautiful Gallery carousel."
                >
                  <div className="splide__track">
                    <ul className="splide__list">
                      <li className="splide__slide services-carousel_main-slide">
                        <p className="services-carousel_main-text">
                          Our team loves building from scratch or updating
                          existing identities. Together we craft and translate a
                          brand strategy into a visual identity, beginning with
                          a logo that tells a story. After that we start working
                          on the color palettes, fonts, imagery, tone of voice,
                          moodboards and mockups. All of this will be translated
                          into a brandbook. Working with accessible tools like
                          Figma, Sketch and Adobe XD makes everything (and easy
                          collaboration) possible. Think bold, think big, think
                          new.
                        </p>
                      </li>
                      <li className="splide__slide services-carousel_main-slide">
                        <p className="services-carousel_main-text">
                          We believe in a - broad spectrum - approach to create
                          state of the art designs and UX frameworks for your
                          digital products, whether it’s a new website or App.
                          Not only by developing the visual design but also
                          adding new trends like 3D art, illustrations and the
                          alignment of video and photography. All to deliver the
                          full brand story to any chosen audience.
                        </p>
                      </li>
                      <li className="splide__slide services-carousel_main-slide">
                        <p className="services-carousel_main-text">
                          We build modular and sustainable solutions that
                          perfectly match our designs and concepts. We are
                          always on the lookout for new tools to adapt to the
                          latest and ever evolving standards. Ranging from
                          robust headless Singe Page Webapps build in React with
                          Nextjs and Gatsbyjs, to quick but highly animated
                          landing pages in Webflow. Always with a friendly CMS
                          as a basis for our future relationship. This gives our
                          clients, plenty freedom for easy and ongoing edits.
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>

              <div className="mbServicesInnerContainer">
                <div className="mbServicesColLeft">
                  <button
                    id="mbBrandingClick"
                    className="button mbServiceClick noselect"
                    // onclick="switchService('Branding')"
                  >
                    Branding
                  </button>
                  <button
                    id="mbDesignClick"
                    className="button mbServiceClick noselect"
                    // onclick="switchService('Design')"
                  >
                    Design
                  </button>
                  <button
                    id="mbDevelopmentClick"
                    className="button mbServiceClick noselect"
                    // onclick="switchService('Development')"
                  >
                    Development
                  </button>
                </div>
                <div className="mbServicesColRight">
                  <article id="mbBrandingContent" className="mbServiceContent">
                    <p className="mbServiceContentText">
                      Our team loves building from scratch or updating existing
                      identities. Together we craft and translate a brand
                      strategy into a visual identity, beginning with a logo
                      that tells a story. After that we start working on the
                      color palettes, fonts, imagery, tone of voice, moodboards
                      and mockups. All of this will be translated into a
                      brandbook. Working with accessible tools like Figma,
                      Sketch and Adobe XD makes everything (and easy
                      collaboration) possible. Think bold, think big, think new.
                    </p>
                    <p className="mbServiceContentServices">
                      Logo / Brandbook / Visual Brand Identity / Strategy /
                      Copywriting
                    </p>
                  </article>
                  <article id="mbDesignContent" className="mbServiceContent">
                    <p className="mbServiceContentText">
                      We believe in a - broad spectrum - approach to create
                      state of the art designs and UX frameworks for your
                      digital products, whether it’s a new website or App. Not
                      only by developing the visual design but also adding new
                      trends like 3D art, illustrations and the alignment of
                      video and photography. All to deliver the full brand story
                      to any chosen audience.
                    </p>
                    <p className="mbServiceContentServices">
                      UX & UI Design / Webdesign / 3D Art / Illustration / Video
                      / Photography
                    </p>
                  </article>
                  <article
                    id="mbDevelopmentContent"
                    className="mbServiceContent"
                  >
                    <p className="mbServiceContentText">
                      We build modular and sustainable solutions that perfectly
                      match our designs and concepts. We are always on the
                      lookout for new tools to adapt to the latest and ever
                      evolving standards. Ranging from robust headless Singe
                      Page Webapps build in React with Nextjs and Gatsbyjs, to
                      quick but highly animated landing pages in Webflow. Always
                      with a friendly CMS as a basis for our future
                      relationship. This gives our clients, plenty freedom for
                      easy and ongoing edits.
                    </p>
                    <p className="mbServiceContentServices">
                      Websites / Webflow / React / Nextjs / Shopify /
                      Landingpages
                    </p>
                  </article>
                </div>
              </div>

              <div className="mbServicesBottomRow">
                <Image
                  src="assets/icons/icon_ux.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconBranding"
                  id="mbServiceIconBranding3"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_sketch.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconBranding"
                  id="mbServiceIconBranding4"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_sketch.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDesign"
                  id="mbServiceIconDesign3"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_xd.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDesign"
                  id="mbServiceIconDesign4"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_next.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDevelopment"
                  id="mbServiceIconDevelopment3"
                  alt=""
                />
                <Image
                  src="assets/icons/icon_gatsby.png"
                  width={500}
                  height={500}
                  className="mbServiceIcon mbServiceIconDevelopment"
                  id="mbServiceIconDevelopment4"
                  alt=""
                />
              </div>
            </div>
          </section> */}

          {/* <footer id="anchorContact" className="footer_container">
            <div className="footer_heads">
              <div className="mbContactHeadsWrapper">
                <Image
                  className="mbFooterHead mbFooterHead1"
                  src="images/hero_head_top.png"
                  width={500}
                  height={500}
                  alt="We Met Before Head Illustration"
                />
                <Image
                  className="mbFooterHead mbFooterHead2"
                  src="images/hero_head_bottom.png"
                  width={500}
                  height={500}
                  alt="We Met Before Head Illustration"
                />
                <div className="mbFooterBoll sphereGradient"></div>
              </div>
            </div>
            <div className="mbContactFooter">
              <div className="mbContactFooterSection mbContactAms">
                <span className="mbContactFooterLocation">AMS</span>
                <ul className="mbContactFooterList mbContactFooterListMargin">
                  <li className="footer-contact_item">Spijkerkade 2</li>
                  <li className="footer-contact_item">1021JS Amsterdam</li>
                  <li className="footer-contact_item">The Netherlands</li>
                </ul>
              </div>
              <div className="mbContactFooterSection mbContactSocial">
                <ul className="mbContactFooterList">
                  <li className="footer-contact_item">
                    <a className="footer-contact_link" href="tel:+31648405400">
                      +31648405400
                    </a>
                  </li>
                  <li className="footer-contact_item">
                    <a
                      className="footer-contact_link"
                      href="mailto:info@wemetbefore.com"
                    >
                      info@wemetbefore.com
                    </a>
                  </li>
                  <li className="footer-contact_item">
                    <a
                      className="footer-contact_link"
                      href="https://www.instagram.com/wemetbefore.studio/"
                      target="_blank"
                    >
                      Instagram
                    </a>
                    /
                    <a
                      className="footer-contact_link"
                      href="https://www.behance.net/WeMetBefore"
                      target="_blank"
                    >
                      Behance
                    </a>
                    /
                    <a
                      className="footer-contact_link"
                      href="https://www.linkedin.com/company/wemetbefore"
                      target="_blank"
                    >
                      LinkedIn
                    </a>
                  </li>
                </ul>
              </div>
              <div className="mbContactFooterSection mbContactBcn">
                <ul className="mbContactFooterList mbContactFooterListMargin">
                  <li className="footer-contact_item">C/ de Magalhães 46</li>
                  <li className="footer-contact_item">08004 Barcelona</li>
                  <li className="footer-contact_item">Spain</li>
                </ul>
                <span className="mbContactFooterLocation">BCN</span>
              </div>
            </div>
          </footer> */}
        </div>
      </main> 

      {/* <footer id="anchorContact" className="footer_container">
        <div className="footer_heads">
          <div className="mbContactHeadsWrapper">
            <Image
              className="mbFooterHead mbFooterHead1"
              src="images/hero_head_top.png"
              alt="We Met Before Head Illustration"
              width={500}
              height={500}
            />
            <Image
              className="mbFooterHead mbFooterHead2"
              src="images/hero_head_bottom.png"
              alt="We Met Before Head Illustration"
              width={500}
              height={500}
            />
            <div className="mbFooterBoll sphereGradient"></div>
          </div>
        </div>
        <div className="mbContactFooter">
          <div className="mbContactFooterSection mbContactAms">
            <span className="mbContactFooterLocation">AMS</span>
            <ul className="mbContactFooterList mbContactFooterListMargin">
              <li className="footer-contact_item">Spijkerkade 2</li>
              <li className="footer-contact_item">1021JS Amsterdam</li>
              <li className="footer-contact_item">The Netherlands</li>
            </ul>
          </div>
          <div className="mbContactFooterSection mbContactSocial">
            <ul className="mbContactFooterList">
              <li className="footer-contact_item">
                <a className="footer-contact_link" href="tel:+31648405400">
                  +31648405400
                </a>
              </li>
              <li className="footer-contact_item">
                <a
                  className="footer-contact_link"
                  href="mailto:info@wemetbefore.com"
                >
                  info@wemetbefore.com
                </a>
              </li>
              <li className="footer-contact_item">
                <a
                  className="footer-contact_link"
                  href="https://www.instagram.com/wemetbefore.studio/"
                  target="_blank"
                >
                  Instagram
                </a>
                /
                <a
                  className="footer-contact_link"
                  href="https://www.behance.net/WeMetBefore"
                  target="_blank"
                >
                  Behance
                </a>
                /
                <a
                  className="footer-contact_link"
                  href="https://www.linkedin.com/company/wemetbefore"
                  target="_blank"
                >
                  LinkedIn
                </a>
              </li>
            </ul>
          </div>
          <div className="mbContactFooterSection mbContactBcn">
            <ul className="mbContactFooterList mbContactFooterListMargin">
              <li className="footer-contact_item">C/ de Magalhães 46</li>
              <li className="footer-contact_item">08004 Barcelona</li>
              <li className="footer-contact_item">Spain</li>
            </ul>
            <span className="mbContactFooterLocation">BCN</span>
          </div>
        </div>
      </footer> */}
    </>
  );
}
