import Script from "next/script";
// import "src/styles/style.scss";

export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
  openGraph: {
    title: "Blog",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
