import Script from "next/script";
import HeroProject from "../src/components/HeroProject/HeroProject";
// import "src/styles/style.scss";

export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
  openGraph: {
    title: "Blog",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="/about/packages/ScrollTrigger.min.js" />
      <Script src="/about/packages/SplitText.min.js" />
      <body>
        {/* <HeroProject /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
